apiVersion: v1
kind: Service
metadata:
  name: service-binding-python-service
spec:
  selector:
    app: service-binding
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-binding
spec:
  selector:
    matchLabels:
       app: service-binding
  replicas: 2
  template:
    metadata:
      labels:
        app: service-binding
    spec:
      containers:
      - name: service-binding
        image: quay.io/xiezhang7/service-binding:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
